
services:
  playlistdl:
    image: playlistdlwithapi:latest
    container_name: playlistdlwithapi
    ports:
      - "5005:5000"
    environment:
      #Direct Server Download
      - ADMIN_USERNAME=admin #Insert unique username here!
      - ADMIN_PASSWORD=password #Insert unique password here!
      
      - AUDIO_DOWNLOAD_PATH=${AUDIO_DOWNLOAD_PATH}  # Use the env variable
      - CLEANUP_INTERVAL=300  # Optional
    volumes:
      - ${AUDIO_DOWNLOAD_PATH}:${AUDIO_DOWNLOAD_PATH}:rw  # Reference env variable here as well
    restart: unless-stopped